### ISSUE TITLE
dont work at  markdown-it v4.+

### ISSUE THREAD

**Issue by suziwen** [andrey-p/markdown-it-classy#5]

**Comment by andrey-p** [comment]
Thanks for that - I'm adding `markdown-it <4.0.0` as a peer dependency for the current version of `markdown-it-classy`, and will put up a version compatible with `markdown-it >= 4.0.0` ASAP.

**Comment by stiang** [comment]
I just ran into this as well. Are you making progress on the new version?

**Comment by qanuj** [comment]
Same trouble, would you be handling this soon ?

**Comment by andrey-p** [comment]
Hey, sorry about the delay on this! Porting to markdown-it v4 turned out to be fairly non-trivial and a bunch of real life things prevented me from getting solid work done on this.

I've got a version that passes all my tests but I'm really not happy with how the code for it looks. I want to reorganize it a bit, and do some more testing on real-world examples and really contrived situations like nested inline elements.

If you need to use this module immediately and you're ok with things potentially breaking, you can find it on [this branch here](https://github.com/andrey-p/markdown-it-classy/tree/markdown-it-v4).

**Comment by andrey-p** [comment]
I've tested this further and decided to release the branch as-is, having this module broken for this long is pretty ridiculous.

The new version is available on NPM. Enjoy!
